### ISSUE TITLE
화면전환 싹 부시기

### ISSUE THREAD

**Issue by lydiacho** [TeamCatchMe/CatchMe-If-You-Android#180]
# 📝 DESCRIPTION
### Describe issue here
놓친 화면전환 싹 넣기

# ☑️ TODO
- [x] 메인 -> 구경하기 (오른쪽 in)
- [x] 구경하기 백버튼 -> 메인 구경하기 (오른쪽 out)
- [x] 캐츄 상세 수정 -> 활동 수정 뷰 (아래 in)
- [x] 리포트 캐츄 클릭 -> 캐츄 상세뷰 (오른쪽 in)
- [x] 설정 닉변 클릭 -> 닉네임 변경뷰 (오른쪽 in)
- [x] 닉변 백버튼 -> 설정 돌아가기 (오른쪽 out)
- [x] 설정 비변 클릭 -> 비번 확인뷰 (오른쪽 in)
- [x] 비변 완료 클릭 -> 설정으로 돌아가기 (오른쪽 out)
- [x] 개발자 정보 클릭 -> 개발자 뷰 (오른쪽 in)
- [x] 개발자 정보에서 뒤로가기 -> 설정으로 돌아가기 ( 오른쪽 out)
- [x] 서비스 탈퇴 클릭 -> 서비스 탈퇴 뷰 (오른쪽 in)
- [x] 서비스 탈퇴 뷰 백버튼 -> 설정 돌아오기 (오른쪽 out)
