### ISSUE TITLE
화면전환 애니메이션 구현

### ISSUE THREAD

**Issue by lydiacho** [TeamCatchMe/CatchMe-If-You-Android#61]
# 📝 DESCRIPTION
### Describe issue here
피그마 화면전환 플로우 기반으로 전환 애니메이션 구현하기

# ☑️ TODO
- [x] 메인 -> 메인카드 : 오른쪽 move-in
- [x] 메인카드 -> 메인 : 오른쪽 move-out
- [ ] 다른 파트원들 액티비티랑 연결 후에 나머지 구현
