### ISSUE TITLE
Refactor Fragments

### ISSUE THREAD

**Issue by SeojinSeojin** [TeamCatchMe/CatchMe-If-You-Android#66]
# 📝 DESCRIPTION
### Describe issue here

# ☑️ TODO
- [ ] Frame Layout을 없애라
- [ ] binding null하게 만들고 은닉하고 onDestroyView에서 화끈하게 없앤다
- [ ] Width, Height 변경하는 함수 수정할 부분 수정
